#pragma once
#include <cstdio>
#include <iostream>
#include <algorithm>
#include "Search.h"
#include "LinkedList.h"
#include "DoubleLinkedList.h"
#include "Dynamic.h"
#include "BinarySearch.h"
#include "Struct.h"
#include "QuickSort.h"
#include "MergeSort.h"